use crate::data_model::{Direction, MovePiece, PlayerMove, WallOrientation, WallPosition};
#[rustfmt::skip]
pub const ALL_MOVES: [PlayerMove; 140] = [
    PlayerMove::MovePiece(MovePiece{direction: Direction::Up, direction_on_collision: Direction::Up}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Up, direction_on_collision: Direction::Left}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Up, direction_on_collision: Direction::Right}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Down, direction_on_collision: Direction::Down}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Down, direction_on_collision: Direction::Left}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Down, direction_on_collision: Direction::Right}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Left, direction_on_collision: Direction::Up}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Left, direction_on_collision: Direction::Down}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Left, direction_on_collision: Direction::Left}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Right, direction_on_collision: Direction::Up}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Right, direction_on_collision: Direction::Down}),
    PlayerMove::MovePiece(MovePiece{direction: Direction::Right, direction_on_collision: Direction::Right}),
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 0, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 1, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 2, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 3, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 4, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 5, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 6, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Horizontal, position: WallPosition { x: 7, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 0, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 1, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 2, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 3, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 4, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 5, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 6, y: 7 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 0 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 1 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 2 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 3 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 4 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 5 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 6 }},
    PlayerMove::PlaceWall { orientation: WallOrientation::Vertical, position: WallPosition { x: 7, y: 7 }},
];
